### PR TITLE
add auto discovery RSS feed

### PR DESCRIPTION
**Pull request by zyhou**
[Some people](https://twitter.com/SachaGreif/status/1471006067387957249) didn't found you RSS feed or web site such as feedly

## Todo

- [x] Add auto discovery RSS feed (https://www.rssboard.org/rss-autodiscovery)

### CODE REVIEW

**Comment by MaximeHeckel** [comment]
You're the first contributor @zyhou ! Thank you so much! 🙏

**Comment by MaximeHeckel** [comment]
Secret issue on CI (probably my TWITTER_API_KEY causing some trouble here 😅 ) will run CI locally today to make sure we're good but I don't see how this could break anything

**Comment by zyhou** [comment]
> Secret issue on CI (probably my TWITTER_API_KEY causing some trouble here sweat_smile ) will run CI locally today to make sure we're good but I don't see how this could break anything

The revert will be easy, if this line broke everything :)

**Review by MaximeHeckel — APPROVED** [review]
✅  Looks good!

**Pull request merged**
